In [11]:
import numpy as np


## b)

In [36]:
matrix_A = np.matrix([[39, 57, 60], [57, 118, 53], [60, 53, 127]])
matrix_B = np.matrix([[10, 9, 26, 3, 26], [9, 62, 8, -5, 85], [26, 8, 72, 10, 50], [3, -5, 10, 2, -1], [26, 85, 50, -1, 138]])

eig_vals_A, eig_vecs_A = np.linalg.eig(matrix_A) 
eig_vals_B, eig_vecs_B = np.linalg.eig(matrix_B)

# the numpy method returns values that are essentially Zero, so I am removing those from my
# eigenvalue array as well as the corresponding eigenvectors
eig_vals_A = np.take(eig_vals_A, [0,2])
eig_vecs_A = eig_vecs_A[:, [0, 2]]

eig_vals_B = np.take(eig_vals_B, [0, 2])
eig_vecs_B = eig_vecs_B[:, [0, 2]]

singulars = []
singulars.append(np.sqrt(eig_vals_A[0]))
singulars.append(np.sqrt(eig_vals_A[1]))
                     

print eig_vals_A
print eig_vals_B


[ 214.6704892   69.3295108]
[ 214.6704892   69.3295108]
[14.651637764976877, 8.3264344592330364]


## c)

In [33]:
# FROM THE NUMPY DOCS:
#The normalized (unit "length") eigenvectors, such that the
#   column ``v[:,i]`` is the eigenvector corresponding to the
#    eigenvalue ``w[i]``.
print "Eigenvectors for Matrix A (M*M):"
print eig_vecs_A[:, 0]
print ".............."
print eig_vecs_A[:, 1]

print "Eigenvectors for Matrix A (MM*):"
print eig_vecs_B[:, 0]
print ".............."
print eig_vecs_B[:, 1]

Eigenvectors for Matrix A (M*M):
[[ 0.42615127]
 [ 0.61500884]
 [ 0.66344497]]
..............
[[-0.01460404]
 [-0.72859799]
 [ 0.68478587]]
Eigenvectors for Matrix A (MM*):
[[-0.16492942]
 [-0.47164732]
 [-0.33647055]
 [-0.00330585]
 [-0.79820031]]
..............
[[ 0.24497323]
 [-0.45330644]
 [ 0.82943965]
 [ 0.16974659]
 [-0.13310656]]


## d)

In [41]:
print "U = " 
print eig_vecs_B
print "......."


print "Σ = "
print np.diag(singulars)
print "......."
print "V* = "
print eig_vecs_A.transpose()

U = 
[[-0.16492942  0.24497323]
 [-0.47164732 -0.45330644]
 [-0.33647055  0.82943965]
 [-0.00330585  0.16974659]
 [-0.79820031 -0.13310656]]
.......
Σ = 
[[ 14.65163776   0.        ]
 [  0.           0.        ]]
.......
V* = 
[[ 0.42615127  0.61500884  0.66344497]
 [-0.01460404 -0.72859799  0.68478587]]


## e)

In [43]:
singulars_copy = singulars

singulars_copy[1] = 0

one_d_approx = np.dot(eig_vecs_B, np.dot(np.diag(singulars_copy), eig_vecs_A.transpose()))

print one_d_approx 

[[-1.02978864 -1.48616035 -1.60320558]
 [-2.94487812 -4.24996055 -4.58467382]
 [-2.10085952 -3.031898   -3.27068057]
 [-0.02064112 -0.02978864 -0.0321347 ]
 [-4.9838143  -7.19249261 -7.75895028]]
